# Scraping: http://www.bbc.co.uk/news

Πάμε να πάρουμε περιεχόμενο από την αρχική σελίδα του BBC News. Θέλουμε:

* Τίτλους (Headlines)
* Συνόψεις (Summary)
* Υπερσυνδέσεις (link)

## Ξεκινώντας

Θέλουμε να **εισάγουμε τα απαραίτητα libraries**.

In [3]:
import requests
from bs4 import BeautifulSoup

Προχωράμε να **κατεβάσουμε την ιστοσελίδα** και *να την εισάγουμε στο BeautifulSoup*.

In [9]:
response = requests.get('https://www.bbc.com/news')
doc = BeautifulSoup(response.text, 'html.parser')

Συνήθως την σελίδα που αναλύουμε στο Beautiful Soup την ονομάζουμε `soup`, αλλά σήμερα θα κάνουμε τη διαφορά και θα την ονομάσουμε `doc`, για να θυμόμαστε ότι είναι ολόκληρο το *document*.

## Προσπάθεια 1η: Παίρνουμε απευθείας τα tags

Αν κοιτάξουμε την σελίδα, προσπαθούμε με το βελάκι να επιλέξουμε τα headlines, αλλά δεν **γίνεται**. Δεν μπορούμε να επιλέξουμε κανέναν τίτλο! Προφανώς πρόκειται για ολόκληρο το BLOCK του άρθρου ή κάτι τέτοιο?

Ευτυχώς γνωρίζουμε λίγο HTML, οπότε μπορούμε να επιλέξουμε από το δεξί πλαίσιο που λέγεται Elements. Πάμε στο `h3` tag, το οποίο ξέρουμε ότι περιέχει τον τίτλο και το περιεχόμενο του.

Χμ, άρα μήπως να πάρουμε απλά όλα τα `h3` tags?

In [11]:
headlines = doc.find_all('h2')

for headline in headlines:
    print(headline.text)

Trump and King hold private talks after royals welcomed to White House with crowds and flypast
US political violence generates a familiar cycle - this time it's in overdrive
United Arab Emirates to quit oil cartel Opec
Why Sam Altman and his former hero Elon Musk are taking their toxic feud to court
'It's bizarre': Californians grapple with revelation that suspected Trump gunman was neighbour
Watch: Jimmy Kimmel defends 'expectant widow' joke after first lady criticism
Russian superyacht sails through Strait of Hormuz despite blockade
The other life of US soldier accused of betting on Maduro's removal
Suspected gunman aged 89 held in Greece after five wounded
Canada's Carney launches a sovereign wealth fund. What is it?
Ex-actor Nathan Chasing Horse jailed for at least 37 years for sexual assault
Man admits plotting attack on Taylor Swift concert in Vienna
Japan Airlines trials humanoid robots as ground handlers
More to explore
Watch as Sabastian Sawe's parents celebrate marathon record
In pictures: King Charles and Queen Camilla at garden party and White House on US state visit
What happened when Rebel Wilson gave evidence in court?
The man who exposed hundreds of British Museum thefts - but didn't live to see justice
Canada's Carney has enjoyed a long political honeymoon. Now comes the test
Why Spotify has no button to filter out AI music
When Attenborough met the gorillas - the story behind his iconic TV moment
Most watched
Watch: Jimmy Kimmel defends 'expectant widow' joke after first lady criticism
Inside Trump press dinner shooting suspect's court appearance
What happened when Rebel Wilson gave evidence in court?
What the King and Queen did on their first day in the US
'I jumped around the house': Sabastian Sawe's parents celebrate marathon record
Also in news
Mexican cartel leader found hiding in a ditch
France murder victim identified after 20 years and suspect arrested
Megan Thee Stallion pulls out of Moulin Rouge show
Third Ukrainian strike hits Russian oil refinery and prompts evacuations
NZ axes plan for WW2 sex slaves statue after Japan protest
Rescuers race to free survivors trapped inside train after fatal Indonesia crash
Swarm of 10,000 bees settles on bike outside Louvre in Paris
Most read
United Arab Emirates to quit oil cartel Opec
Russian superyacht sails through Strait of Hormuz despite blockade
Jimmy Kimmel rejects White House criticism over Melania widow joke
'It's bizarre': Californians grapple with revelation that suspected Trump gunman was neighbour
In pictures: King Charles and Queen Camilla at garden party and White House on US state visit
US political violence generates a familiar cycle - this time it's in overdrive
Swarm of 10,000 bees settles on bike outside Louvre in Paris
Canada's Carney launches a sovereign wealth fund. What is it?
Why Sam Altman and his former hero Elon Musk are taking their toxic feud to court
Japan Airlines trials humanoid robots as ground handlers
Sport
Man City left frustrated by fixture pile-up
Ranking the players who could decide Champions League semi-finals
The tactical fluidity that makes PSG so impressive
World Championship quarter-finals - Higgins v Robertson; Wu v Vafaei - follow updates
'I lived all my dreams' - Stones to leave Man City
Sinner beats Norrie to equal historic winning run
Liked by Flintoff & different to Crawley - is Gay England's next opener?

Αρκετά απλό, αλλά? ...λείπει το link και το summary.

Ok, οπότε μπορούμε να δοκιμάσουμε να πάρουμε όλα τα `a` tags, αλλά σίγουρα θα πάρουμε μαζί με αυτά που θέλουμε και αρκετά σκουπίδια που θα περιέχουν `a` tags - όπως π.χ. το περιεχόμενο στο footer της σελίδας κ.λπ. Πάμε να δούμε μήπως μέσα στα `a` tags του άρθρου υπάρχει κάποιο ξεχωριστό class?

Αν παρατηρήσουμε καλά θα δούμε ότι όντως είναι `class="gs-c-promo-heading nw-o-link-split__anchor gs-o-faux-block-link__overlay-link gel-pica-bold"`. Αυτό δεν είναι μόνο ένα class, είναι **ΠΟΛΛΑ classes**.

* `gs-c-promo-heading`
* `nw-o-link-split__anchor`
* `gs-o-faux-block-link__overlay-link`
* `gel-pica-bold`

Κάπου εδώ αρχίζουμε τις μαντεψιές. Ας δοκιμάσουμε πρώτα το `gs-c-promo-heading` που φαίνεται αρκετά λογικό να είναι το σωστό!

In [23]:
base_url = "https://www.bbc.com"

for link in doc.select("a[data-testid='internal-link']"):
    title = link.get_text(strip=True)
    href = link.get("href")

    if href and href.startswith("/news") and title:
        print(title)
        print(base_url + href)
        print()

US political violence generates a familiar cycle - this time it's in overdriveIn modern America, it seems violence of this kind has become an ever-present storm that can strike anywhere and at any moment.16 hrs agoUS & Canada
https://www.bbc.com/news/articles/cje4eeyq27lo

United Arab Emirates to quit oil cartel OpecThe UAE's decision, after nearly 60 years of membership, is seen as a potential death knell for the oil cartel.Just nowBusiness
https://www.bbc.com/news/articles/cj4pxwlr52yo

Why Sam Altman and his former hero Elon Musk are taking their toxic feud to courtThe battle between the AI big hitters has largely played out on social media. Now it is coming to the courtroom.48 mins ago
https://www.bbc.com/news/articles/cn8dedv8w8xo

'It's bizarre': Californians grapple with revelation that suspected Trump gunman was neighbourPeople living near the man charged with the attempted assassination of Trump  say they were shocked to see their neighbour on TV.5 hrs agoUS & Canada
https://www.bbc.com/news/articles/c392knk3w2jo

Watch: Jimmy Kimmel defends 'expectant widow' joke after first lady criticismFirst Lady Melania Trump described the joke as "hateful and violent", with the White House urging ABC to fire the comedian.3 hrs agoUS & Canada
https://www.bbc.com/news/videos/c62d4n5rzr7o

Russian superyacht sails through Strait of Hormuz despite blockadeThe 141m-long vessel, linked to a close ally of Russian President Vladimir Putin, cleared the waterway despite an ongoing blockade.4 hrs agoWorld
https://www.bbc.com/news/articles/cm2pn8zdxdjo

The other life of US soldier accused of betting on Maduro's removalThe Army officer charged with using classified information to win $400,000 is also a real estate investor with rave reviews on Airbnb.7 hrs agoWorld
https://www.bbc.com/news/articles/clyxd5wrr0wo

Suspected gunman aged 89 held in Greece after five wounded
https://www.bbc.com/news/articles/cyv2pmz2v86o

Canada's Carney launches a sovereign wealth fund. What is it?
https://www.bbc.com/news/articles/c98m800r28qo

Ex-actor Nathan Chasing Horse jailed for at least 37 years for sexual assault
https://www.bbc.com/news/articles/cx218vkdvpgo

Man admits plotting attack on Taylor Swift concert in Vienna
https://www.bbc.com/news/articles/c05d5qgprjzo

Japan Airlines trials humanoid robots as ground handlers
https://www.bbc.com/news/articles/cpwp87j1llvo

Musk v Altman: The tech billionaires and former friends now facing off in courtThe battle between the AI big hitters has largely played out on social media. Now it is coming to the courtroom.48 mins ago
https://www.bbc.com/news/articles/cn8dedv8w8xo

Watch as Sabastian Sawe's parents celebrate marathon recordEmily and Simion Sawe share their pride at the runner's historic sub-two-hour marathon win.6 hrs agoAfrica
https://www.bbc.com/news/videos/cn0pl57xlppo

Will Mexico City's airport be ready for the World Cup?The BBC takes a closer look at major renovations at Benito Juárez International Airport aimed at boosting capacity ahead of the 2026 World Cup.3 hrs agoLatin America
https://www.bbc.com/news/videos/cz7231qx88qo

The man who exposed hundreds of British Museum thefts - but didn't live to see justiceDr Ittai Gradel made global headlines after exposing the thefts of many artefacts from the British Museum.9 hrs agoCulture
https://www.bbc.com/news/articles/c1mk2pr39k7o

Canada's Carney has enjoyed a long political honeymoon. Now comes the testGlobal acclaim and domestic political gains have defined Mark Carney's first year as Canada's PM. He now faces pressure to deliver on his bold promises.4 hrs agoUS & Canada
https://www.bbc.com/news/articles/c70d249rd0go

Why Spotify has no button to filter out AI musicMusic streamer Deezer allows users to filter out AI music, so why does Spotify not offer the same?17 hrs agoTechnology
https://www.bbc.com/news/articles/cd7jpg4w181o

When Attenborough met the gorillas - the story behind his iconic TV momentTwo new documentaries explore the the fascinating tale behind the defining image of Attenborough's career.1 day agoCulture
https://www.bbc.com/news/articles/ce9n794g42zo

1Watch: Jimmy Kimmel defends 'expectant widow' joke after first lady criticism
https://www.bbc.com/news/videos/c62d4n5rzr7o

2Inside Trump press dinner shooting suspect's court appearance
https://www.bbc.com/news/videos/cj6p277r3k4o

3What happened when Rebel Wilson gave evidence in court?
https://www.bbc.com/news/videos/cwy27njv3wvo

4What the King and Queen did on their first day in the US
https://www.bbc.com/news/videos/c78q59ynj4vo

5'I jumped around the house': Sabastian Sawe's parents celebrate marathon record
https://www.bbc.com/news/videos/cn0pl57xlppo

Mexican cartel leader found hiding in a ditchAudias Flores Silva was a key player in the Jalisco New Generation Cartel, whose top leader was killed two months ago.5 hrs agoLatin America
https://www.bbc.com/news/articles/cj6p2r9gk8go

France murder victim identified after 20 years and suspect arrestedHakima Boukerouis is the fifth woman to be identified through an international police campaign.2 hrs agoEurope
https://www.bbc.com/news/articles/ckg9g8pwggqo

Suspect charged with attempted assassination of Trump at Washington dinnerInvestigators say the 31-year-old California man wanted to kill as many high-level officials as possible.16 hrs agoUS & Canada
https://www.bbc.com/news/articles/cew7wez72vxo

Third Ukrainian strike hits Russian oil refinery and prompts evacuationsResidents near a burning refinery in Tuapse are told to leave, and the Kremlin accuses Kyiv of destabilising global energy markets.2 hrs agoEurope
https://www.bbc.com/news/articles/cvgzd4qk7qgo

NZ axes plan for WW2 sex slaves statue after Japan protestTokyo had warned that installing the structure in Auckland could jeopardise diplomatic relations.8 hrs agoAsia
https://www.bbc.com/news/articles/c62r8g6m541o

Ghana's military hunts those behind convoy attack on northern highwayThree civilians and seven gunmen were killed in an area where there has been a protracted chieftaincy dispute.4 hrs agoAfrica
https://www.bbc.com/news/articles/c172g50rz7jo

Swarm of 10,000 bees settles on bike outside Louvre in ParisThe swarm gathers underneath the saddle of a bike locked to the railings of a metro station.2 hrs agoEurope
https://www.bbc.com/news/articles/c70vjx99w2vo

1United Arab Emirates to quit oil cartel Opec
https://www.bbc.com/news/articles/cj4pxwlr52yo

2Russian superyacht sails through Strait of Hormuz despite blockade
https://www.bbc.com/news/articles/cm2pn8zdxdjo

3'It's bizarre': Californians grapple with revelation that suspected Trump gunman was neighbour
https://www.bbc.com/news/articles/c392knk3w2jo

4The other life of US soldier accused of betting on Maduro's removal
https://www.bbc.com/news/articles/clyxd5wrr0wo

5Jimmy Kimmel rejects White House criticism over Melania widow joke
https://www.bbc.com/news/articles/c04x40d4424o

6US political violence generates a familiar cycle - this time it's in overdrive
https://www.bbc.com/news/articles/cje4eeyq27lo

7In pictures: King Charles and Queen Camilla at garden party and White House on US state visit
https://www.bbc.com/news/articles/c86e6z26xdpo

8Swarm of 10,000 bees settles on bike outside Louvre in Paris
https://www.bbc.com/news/articles/c70vjx99w2vo

9Canada's Carney launches a sovereign wealth fund. What is it?
https://www.bbc.com/news/articles/c98m800r28qo

10Japan Airlines trials humanoid robots as ground handlers
https://www.bbc.com/news/articles/cpwp87j1llvo

News
https://www.bbc.com/news

In [26]:
cards = doc.find_all('div', {'class': 'sc-feaf8701-1 dzYnRP'})

for card in cards:
    title = card.find('h2')
    if title:
        print(title.get_text(strip=True))

Trump and King hold private talks after royals welcomed to White House with crowds and flypast
US political violence generates a familiar cycle - this time it's in overdrive
United Arab Emirates to quit oil cartel Opec
Why Sam Altman and his former hero Elon Musk are taking their toxic feud to court
'It's bizarre': Californians grapple with revelation that suspected Trump gunman was neighbour
Watch: Jimmy Kimmel defends 'expectant widow' joke after first lady criticism
Russian superyacht sails through Strait of Hormuz despite blockade
The other life of US soldier accused of betting on Maduro's removal
Suspected gunman aged 89 held in Greece after five wounded
Canada's Carney launches a sovereign wealth fund. What is it?
Ex-actor Nathan Chasing Horse jailed for at least 37 years for sexual assault
Man admits plotting attack on Taylor Swift concert in Vienna
Japan Airlines trials humanoid robots as ground handlers
Musk v Altman: The tech billionaires and former friends now facing off in court
Watch as Sabastian Sawe's parents celebrate marathon record
Will Mexico City's airport be ready for the World Cup?
The man who exposed hundreds of British Museum thefts - but didn't live to see justice
Canada's Carney has enjoyed a long political honeymoon. Now comes the test
Why Spotify has no button to filter out AI music
When Attenborough met the gorillas - the story behind his iconic TV moment
Mexican cartel leader found hiding in a ditch
France murder victim identified after 20 years and suspect arrested
Suspect charged with attempted assassination of Trump at Washington dinner
Third Ukrainian strike hits Russian oil refinery and prompts evacuations
NZ axes plan for WW2 sex slaves statue after Japan protest
Ghana's military hunts those behind convoy attack on northern highway
Swarm of 10,000 bees settles on bike outside Louvre in Paris
Man City left frustrated by fixture pile-up
Ranking the players who could decide Champions League semi-finals
The tactical fluidity that makes PSG so impressive
World Championship quarter-finals - Higgins v Robertson; Wu v Vafaei - follow updates
'I lived all my dreams' - Stones to leave Man City
Sinner beats Norrie to equal historic winning run
Liked by Flintoff & different to Crawley - is Gay England's next opener?

In [24]:
for link in doc.select("a[data-testid='internal-link'] h2"):
    print(link.get_text(strip=True))

US political violence generates a familiar cycle - this time it's in overdrive
United Arab Emirates to quit oil cartel Opec
Why Sam Altman and his former hero Elon Musk are taking their toxic feud to court
'It's bizarre': Californians grapple with revelation that suspected Trump gunman was neighbour
Watch: Jimmy Kimmel defends 'expectant widow' joke after first lady criticism
Russian superyacht sails through Strait of Hormuz despite blockade
The other life of US soldier accused of betting on Maduro's removal
Suspected gunman aged 89 held in Greece after five wounded
Canada's Carney launches a sovereign wealth fund. What is it?
Ex-actor Nathan Chasing Horse jailed for at least 37 years for sexual assault
Man admits plotting attack on Taylor Swift concert in Vienna
Japan Airlines trials humanoid robots as ground handlers
Musk v Altman: The tech billionaires and former friends now facing off in court
Watch as Sabastian Sawe's parents celebrate marathon record
Will Mexico City's airport be ready for the World Cup?
The man who exposed hundreds of British Museum thefts - but didn't live to see justice
Canada's Carney has enjoyed a long political honeymoon. Now comes the test
Why Spotify has no button to filter out AI music
When Attenborough met the gorillas - the story behind his iconic TV moment
Watch: Jimmy Kimmel defends 'expectant widow' joke after first lady criticism
Inside Trump press dinner shooting suspect's court appearance
What happened when Rebel Wilson gave evidence in court?
What the King and Queen did on their first day in the US
'I jumped around the house': Sabastian Sawe's parents celebrate marathon record
Mexican cartel leader found hiding in a ditch
France murder victim identified after 20 years and suspect arrested
Suspect charged with attempted assassination of Trump at Washington dinner
Third Ukrainian strike hits Russian oil refinery and prompts evacuations
NZ axes plan for WW2 sex slaves statue after Japan protest
Ghana's military hunts those behind convoy attack on northern highway
Swarm of 10,000 bees settles on bike outside Louvre in Paris
United Arab Emirates to quit oil cartel Opec
Russian superyacht sails through Strait of Hormuz despite blockade
'It's bizarre': Californians grapple with revelation that suspected Trump gunman was neighbour
The other life of US soldier accused of betting on Maduro's removal
Jimmy Kimmel rejects White House criticism over Melania widow joke
US political violence generates a familiar cycle - this time it's in overdrive
In pictures: King Charles and Queen Camilla at garden party and White House on US state visit
Swarm of 10,000 bees settles on bike outside Louvre in Paris
Canada's Carney launches a sovereign wealth fund. What is it?
Japan Airlines trials humanoid robots as ground handlers
Man City left frustrated by fixture pile-up
Ranking the players who could decide Champions League semi-finals
The tactical fluidity that makes PSG so impressive
'I lived all my dreams' - Stones to leave Man City
Sinner beats Norrie to equal historic winning run
Liked by Flintoff & different to Crawley - is Gay England's next opener?

In [20]:
import requests
from bs4 import BeautifulSoup

url = "https://www.bbc.com/news"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
doc = BeautifulSoup(response.text, "html.parser")

for h in doc.select("[data-testid='card-headline']"):
    parent = h.find_parent("a")

    if parent:
        link = parent.get("href")

        if link:
            # κάνουμε full url
            if link.startswith("/"):
                link = "https://www.bbc.com" + link

            print(link)

https://www.bbc.com/news/live/c4g5lly7qg8t
https://www.bbc.com/news/articles/cje4eeyq27lo
https://www.bbc.com/news/articles/cj4pxwlr52yo
https://www.bbc.com/news/articles/cn8dedv8w8xo
https://www.bbc.com/news/articles/c392knk3w2jo
https://www.bbc.com/news/videos/c62d4n5rzr7o
https://www.bbc.com/news/articles/cm2pn8zdxdjo
https://www.bbc.com/news/articles/clyxd5wrr0wo
https://www.bbc.com/news/articles/cyv2pmz2v86o
https://www.bbc.com/news/articles/c98m800r28qo
https://www.bbc.com/news/articles/cx218vkdvpgo
https://www.bbc.com/news/articles/c05d5qgprjzo
https://www.bbc.com/news/articles/cpwp87j1llvo
https://www.bbc.com/news/articles/cn8dedv8w8xo
https://www.bbc.com/news/videos/cn0pl57xlppo
https://www.bbc.com/news/videos/cz7231qx88qo
https://www.bbc.com/news/articles/c1mk2pr39k7o
https://www.bbc.com/news/articles/c70d249rd0go
https://www.bbc.com/news/articles/cd7jpg4w181o
https://www.bbc.com/news/articles/ce9n794g42zo
https://www.bbc.com/news/videos/c62d4n5rzr7o
https://www.bbc.com/news/videos/cj6p277r3k4o
https://www.bbc.com/news/videos/cwy27njv3wvo
https://www.bbc.com/news/videos/c78q59ynj4vo
https://www.bbc.com/news/videos/cn0pl57xlppo
https://www.bbc.com/news/articles/cj6p2r9gk8go
https://www.bbc.com/news/articles/ckg9g8pwggqo
https://www.bbc.com/news/articles/cew7wez72vxo
https://www.bbc.com/news/articles/cvgzd4qk7qgo
https://www.bbc.com/news/articles/c62r8g6m541o
https://www.bbc.com/news/articles/c172g50rz7jo
https://www.bbc.com/news/articles/c70vjx99w2vo
https://www.bbc.com/news/articles/cj4pxwlr52yo
https://www.bbc.com/news/articles/cm2pn8zdxdjo
https://www.bbc.com/news/articles/c392knk3w2jo
https://www.bbc.com/news/articles/clyxd5wrr0wo
https://www.bbc.com/news/articles/c04x40d4424o
https://www.bbc.com/news/articles/cje4eeyq27lo
https://www.bbc.com/news/articles/c86e6z26xdpo
https://www.bbc.com/news/articles/c70vjx99w2vo
https://www.bbc.com/news/articles/c98m800r28qo
https://www.bbc.com/news/articles/cpwp87j1llvo
https://www.bbc.com/sport/football/articles/cm2pn84y1r3o
https://www.bbc.com/sport/football/articles/c5yw5g3e7nko
https://www.bbc.com/sport/football/articles/cx2w2d178j5o
https://www.bbc.com/sport/snooker/live/cn0wk5wy9d0t
https://www.bbc.com/sport/football/articles/clypwjeydnjo
https://www.bbc.com/sport/tennis/articles/cd0p5vx1g34o
https://www.bbc.com/sport/cricket/articles/cy91937e94go

Το αποτέλεσμα φαίνεται μια χαρά! Παίρνει το κείμενο του `h3`, γιατί το `h3` βρίσκεται μέσα στο `a` tag, αλλά δεν περιέχει το *link* του URL. Ας ρίξουμε μια ματιά στο `a` tag...

    <a class="gs-c-promo-heading nw-o-link-split__anchor gs-o-faux-block-link__overlay-link gel-pica-bold" href="/news/world-middle-east-39302560">
   
...το URL κρύβεται μέσα στην ιδιότητα `href`. Αν πάρουμε το link, είναι εύκολο να πάρουμε μετά το attribute, απλά χρησιμοποιούμε το`['href']`

In [ ]:
links = doc.find_all('a', { 'class': 'gs-c-promo-heading' })

for link in links:
    print(link.text)
    print(link['href'])

Ωραίο, ε? Απλά τώρα μας μένει ένα τελευταίο πρόβλημα: **δεν έχουμε τα summaries**. Αλλά οκ, μπορούμε να χρησιμοποιήσουμε τον Inspector για να διαλέξουμε ένα...

    <p class="gs-c-promo-summary gel-long-primer gs-u-mt nw-c-promo-summary">Trade and Nato are high on the agenda as the much-anticipated Washington talks begin.</p>

Και πάλι, πρέπει να διαλέξουμε ένα από όλα αυτά, ας δοκιμάσουμε το `gs-c-promo-summary` που φαίνεται καλό.

In [ ]:
summaries = doc.find_all('p', { 'class': 'gs-c-promo-summary' })

for summary in summaries:
    print(summary.text)

Ωραία, αλλά **τώρα έχουμε κολλήσει:** δεν υπάρχει τρόπος να συνδυάσουμε και τα headlines και τα links με τα summaries και ακόμη και αν υπήρχε (ίσως με `zip`), δεν θα ήμασταν σίγουροι ότι είναι σωστό το ματσάρισμα.

Άρα τι κάνουμε τώρα?

## Προσπάθεια 2η: Parent elements

Όταν επιλέγουμε ένα element - ένα link και το κείμενο του, ή μια λίστα με headlines - μας ενδιαφέρει μόνο το element που κοιτάμε. Μερικές φορές όμως, **πρέπει να πάρουμε πολλά διαφορετικά elements την ίδια στιγμή.** Όταν συμβαίνει αυτό πρέπει να δούμε τι κοινό έχουν όλα αυτά μαζί.

Αν κοιτάξουμε το summary, το link και τον τίτλο, ίσως βρούμε κάτι σαν το παρακάτω. **Είναι γιγάντιο, αλλά τι να κάνουμε αυτό θέλουμε.**

	<div class="gs-c-promo nw-c-promo gs-o-faux-block-link gs-u-pb gs-u-pb+@m gs-c-promo--inline gs-c-promo--stacked@m nw-u-w-auto gs-c-promo--flex" data-entityid="container-top-stories#3">
		<div class="gs-c-promo-image gs-u-display-none gs-u-display-inline-block@xs gel-1/2@xs gel-1/1@m">
			<div class="gs-o-media-island">
				<div class="gs-o-responsive-image gs-o-responsive-image--16by9"><img alt="Yemeni police gather round bodies of Somali refugees (17/03/19)" class="qa-lazyload-image lazyautosizes lazyloaded" data-sizes="auto" data-srcset="https://ichef.bbci.co.uk/live-experience/cps/240/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 240w, https://ichef.bbci.co.uk/live-experience/cps/320/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 320w, https://ichef.bbci.co.uk/live-experience/cps/480/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 480w, https://ichef.bbci.co.uk/live-experience/cps/624/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 624w, https://ichef.bbci.co.uk/live-experience/cps/800/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 800w" data-widths="[240,320,480,624,800]" sizes="177px" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" srcset="https://ichef.bbci.co.uk/live-experience/cps/240/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 240w, https://ichef.bbci.co.uk/live-experience/cps/320/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 320w, https://ichef.bbci.co.uk/live-experience/cps/480/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 480w, https://ichef.bbci.co.uk/live-experience/cps/624/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 624w, https://ichef.bbci.co.uk/live-experience/cps/800/cpsprodpb/14F5A/production/_95205858_hi038526789.jpg 800w"></div>
			</div>
		</div>
		<div class="gs-c-promo-body gel-1/2@xs gel-1/1@m gs-u-mt@m">
			<div>
				<a class="gs-c-promo-heading nw-o-link-split__anchor gs-o-faux-block-link__overlay-link gel-pica-bold" href="/news/world-middle-east-39302560">
				<h3 class="gs-c-promo-heading__title gel-pica-bold nw-o-link-split__text">Attack on Yemen migrant boat kills 42</h3></a>
				<p class="gs-c-promo-summary gel-long-primer gs-u-mt nw-c-promo-summary">It is unclear who was behind a helicopter attack which killed 42 refugees and injured 80.</p>
			</div>
			<ul class="gs-o-list-inline gs-o-list-inline--divided gel-brevier gs-u-mt-">
				<li><span class="gs-c-timestamp gs-o-bullet gs-o-bullet- nw-c-timestamp"><span class="gs-o-bullet__icon gel-icon"><svg viewbox="0 0 32 32">
				<polygon points="17,15.4 17,6 15,6 15,16.6 23.8,21.7 24.8,19.9"></polygon>
				<path d="M16,4c6.6,0,12,5.4,12,12c0,6.6-5.4,12-12,12S4,22.6,4,16C4,9.4,9.4,4,16,4 M16,0C7.2,0,0,7.2,0,16c0,8.8,7.2,16,16,16 s16-7.2,16-16C32,7.2,24.8,0,16,0L16,0z"></path></svg></span><time class="gs-o-bullet__text date qa-status-date relative-time" data-datetime="1h" data-seconds="1489768430" data-timestamp-inserted="true" datetime="2017-03-17T16:33:50.000Z">48 minutes ago</time></span></li>
				<li>
					<a aria-label="From Middle East" class="gs-c-section-link gs-c-section-link--truncate nw-c-section-link nw-o-link nw-o-link--no-visited-state" href="/news/world/middle_east"><span aria-hidden="true">Middle East</span></a>
				</li>
			</ul>
		</div>
	</div>

To πάνω πάνω κομμάτι λέγεται **parent element**, όλα τα άλλα elements βρίσκονται μέσα σε αυτό. Αν θέλουμε να το πάρουμε όλο μαζί, τότε πρέπει πρώτα να παίρνουμε τον κάθε γονέα (parent) κάθε *είδηση* και μετά να πάρουμε τα επιμέρους κομμάτια που υπάρχουν μέσα π.χ. headline, links, εικόνες κ.λπ.

Tο κομμάτι του class είναι `class="gs-c-promo nw-c-promo gs-o-faux-block-link gs-u-pb gs-u-pb+@m gs-c-promo--inline gs-c-promo--stacked@m nw-u-w-auto gs-c-promo--flex" data-entityid="container-top-stories#3"`, το οποίο εντάξει όντως είναι κάπως τρομακτικό, αλλά θα δοκιμάσουμε το `gs-c-promo` και ίσως δουλέψει.

In [ ]:
stories = doc.find_all('div', { 'class': 'gs-c-promo' })
for story in stories:
    print(story.text)



Προφανώς δεν μπορούμε να χρησιμοποιήσουμε το `.text` γιατί θα πάρει *τα πάντα* που περιέχουν κείμενο, και το headline *και* το summary. Αντιθέτως αυτό που πρέπει να κάνουμε είναι

* ΒΗΜΑ ΕΝΑ: Χρησιμοποιούμε το doc για να πάρουμε την είδηση
* ΒΗΜΑ ΔΥΟ: Χρησιμοποιούμε την είδηση για να πάρουμε τον τίτλο
* ΒΗΜΑ ΤΡΙΑ: Χρησιμοποιούμε την είδηση για να πάρουμε τον link
* ΒΗΜΑ ΤΕΣΣΕΡΑ: Χρησιμοποιούμε την είδηση για να πάρουμε την σύνοψη

### ΒΗΜΑ ΕΝΑ: Χρησιμοποιούμε το doc για να πάρουμε την είδηση (story)

In [ ]:
stories = doc.find_all('div', { 'class': 'gs-c-promo' })
for story in stories:
    print("This is a story")

## ΒΗΜΑ ΔΥΟ + ΤΡΙΑ: Χρησιμοποιούμε την είδηση για να πάρουμε τον τίτλο

Τώρα μπορούμε να κάνουμε ακριβώς το ίδιο για να πάρουμε τον τίτλο και το link, και μετά με το `['href']` να πάρουμε το link του URL.

In [31]:
cards = doc.select(
    'div[data-testid="card-text-wrapper"], '
    'div[data-testid="chester-article"]'
)

for card in cards:
    title = card.select_one('h2[data-testid="card-headline"]')
    desc = card.select_one('p[data-testid="card-description"]')
    link = card.find_parent('a')

    if not title:
        continue

    print("THIS IS A STORY")
    print("Τίτλος:", title.get_text(strip=True))

    if desc:
        print("Περίληψη:", desc.get_text(strip=True))
    else:
        print("Περίληψη: Δεν υπάρχει")

    if link and link.has_attr('href'):
        href = link['href']
        if href.startswith('/'):
            href = 'https://www.bbc.com' + href
        print("Link:", href)
    else:
        print("Link: Δεν βρέθηκε")

    print("-" * 50)

THIS IS A STORY
Τίτλος: US political violence generates a familiar cycle - this time it's in overdrive
Περίληψη: In modern America, it seems violence of this kind has become an ever-present storm that can strike anywhere and at any moment.
Link: https://www.bbc.com/news/articles/cje4eeyq27lo
--------------------------------------------------
THIS IS A STORY
Τίτλος: United Arab Emirates to quit oil cartel Opec
Περίληψη: The UAE's decision, after nearly 60 years of membership, is seen as a potential death knell for the oil cartel.
Link: https://www.bbc.com/news/articles/cj4pxwlr52yo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Why Sam Altman and his former hero Elon Musk are taking their toxic feud to court
Περίληψη: The battle between the AI big hitters has largely played out on social media. Now it is coming to the courtroom.
Link: https://www.bbc.com/news/articles/cn8dedv8w8xo
--------------------------------------------------
THIS IS A STORY
Τίτλος: 'It's bizarre': Californians grapple with revelation that suspected Trump gunman was neighbour
Περίληψη: People living near the man charged with the attempted assassination of Trump  say they were shocked to see their neighbour on TV.
Link: https://www.bbc.com/news/articles/c392knk3w2jo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Watch: Jimmy Kimmel defends 'expectant widow' joke after first lady criticism
Περίληψη: First Lady Melania Trump described the joke as "hateful and violent", with the White House urging ABC to fire the comedian.
Link: https://www.bbc.com/news/videos/c62d4n5rzr7o
--------------------------------------------------
THIS IS A STORY
Τίτλος: Russian superyacht sails through Strait of Hormuz despite blockade
Περίληψη: The 141m-long vessel, linked to a close ally of Russian President Vladimir Putin, cleared the waterway despite an ongoing blockade.
Link: https://www.bbc.com/news/articles/cm2pn8zdxdjo
--------------------------------------------------
THIS IS A STORY
Τίτλος: The other life of US soldier accused of betting on Maduro's removal
Περίληψη: The Army officer charged with using classified information to win $400,000 is also a real estate investor with rave reviews on Airbnb.
Link: https://www.bbc.com/news/articles/clyxd5wrr0wo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Suspected gunman aged 89 held in Greece after five wounded
Περίληψη: Δεν υπάρχει
Link: https://www.bbc.com/news/articles/cyv2pmz2v86o
--------------------------------------------------
THIS IS A STORY
Τίτλος: Canada's Carney launches a sovereign wealth fund. What is it?
Περίληψη: Δεν υπάρχει
Link: https://www.bbc.com/news/articles/c98m800r28qo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Ex-actor Nathan Chasing Horse jailed for at least 37 years for sexual assault
Περίληψη: Δεν υπάρχει
Link: https://www.bbc.com/news/articles/cx218vkdvpgo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Man admits plotting attack on Taylor Swift concert in Vienna
Περίληψη: Δεν υπάρχει
Link: https://www.bbc.com/news/articles/c05d5qgprjzo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Japan Airlines trials humanoid robots as ground handlers
Περίληψη: Δεν υπάρχει
Link: https://www.bbc.com/news/articles/cpwp87j1llvo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Watch as Sabastian Sawe's parents celebrate marathon record
Περίληψη: Emily and Simion Sawe share their pride at the runner's historic sub-two-hour marathon win.
Link: https://www.bbc.com/news/videos/cn0pl57xlppo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Will Mexico City's airport be ready for the World Cup?
Περίληψη: The BBC takes a closer look at major renovations at Benito Juárez International Airport aimed at boosting capacity ahead of the 2026 World Cup.
Link: https://www.bbc.com/news/videos/cz7231qx88qo
--------------------------------------------------
THIS IS A STORY
Τίτλος: The man who exposed hundreds of British Museum thefts - but didn't live to see justice
Περίληψη: Dr Ittai Gradel made global headlines after exposing the thefts of many artefacts from the British Museum.
Link: https://www.bbc.com/news/articles/c1mk2pr39k7o
--------------------------------------------------
THIS IS A STORY
Τίτλος: Canada's Carney has enjoyed a long political honeymoon. Now comes the test
Περίληψη: Global acclaim and domestic political gains have defined Mark Carney's first year as Canada's PM. He now faces pressure to deliver on his bold promises.
Link: https://www.bbc.com/news/articles/c70d249rd0go
--------------------------------------------------
THIS IS A STORY
Τίτλος: Why Spotify has no button to filter out AI music
Περίληψη: Music streamer Deezer allows users to filter out AI music, so why does Spotify not offer the same?
Link: https://www.bbc.com/news/articles/cd7jpg4w181o
--------------------------------------------------
THIS IS A STORY
Τίτλος: When Attenborough met the gorillas - the story behind his iconic TV moment
Περίληψη: Two new documentaries explore the the fascinating tale behind the defining image of Attenborough's career.
Link: https://www.bbc.com/news/articles/ce9n794g42zo
--------------------------------------------------
THIS IS A STORY
Τίτλος: France murder victim identified after 20 years and suspect arrested
Περίληψη: Hakima Boukerouis is the fifth woman to be identified through an international police campaign.
Link: https://www.bbc.com/news/articles/ckg9g8pwggqo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Suspect charged with attempted assassination of Trump at Washington dinner
Περίληψη: Investigators say the 31-year-old California man wanted to kill as many high-level officials as possible.
Link: https://www.bbc.com/news/articles/cew7wez72vxo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Third Ukrainian strike hits Russian oil refinery and prompts evacuations
Περίληψη: Residents near a burning refinery in Tuapse are told to leave, and the Kremlin accuses Kyiv of destabilising global energy markets.
Link: https://www.bbc.com/news/articles/cvgzd4qk7qgo
--------------------------------------------------
THIS IS A STORY
Τίτλος: NZ axes plan for WW2 sex slaves statue after Japan protest
Περίληψη: Tokyo had warned that installing the structure in Auckland could jeopardise diplomatic relations.
Link: https://www.bbc.com/news/articles/c62r8g6m541o
--------------------------------------------------
THIS IS A STORY
Τίτλος: Ghana's military hunts those behind convoy attack on northern highway
Περίληψη: Three civilians and seven gunmen were killed in an area where there has been a protracted chieftaincy dispute.
Link: https://www.bbc.com/news/articles/c172g50rz7jo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Swarm of 10,000 bees settles on bike outside Louvre in Paris
Περίληψη: The swarm gathers underneath the saddle of a bike locked to the railings of a metro station.
Link: https://www.bbc.com/news/articles/c70vjx99w2vo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Ranking the players who could decide Champions League semi-finals
Περίληψη: Which players will prove key to their team’s chances in the Champions League last four? We've ranked the top 10.
Link: https://www.bbc.com/sport/football/articles/c5yw5g3e7nko
--------------------------------------------------
THIS IS A STORY
Τίτλος: The tactical fluidity that makes PSG so impressive
Περίληψη: Despite boasting squads that have included the likes of Lionel Messi, Neymar and Kylian Mbappe, it is the current Paris St-Germain side that is playing the club's most impressive football.
Link: https://www.bbc.com/sport/football/articles/cx2w2d178j5o
--------------------------------------------------
THIS IS A STORY
Τίτλος: World Championship quarter-finals - Higgins v Robertson; Wu v Vafaei - follow updates
Περίληψη: Watch live coverage and follow text updates of the World Championship quarter-finals at the Crucible Theatre, Sheffield.
Link: https://www.bbc.com/sport/snooker/live/cn0wk5wy9d0t
--------------------------------------------------
THIS IS A STORY
Τίτλος: 'I lived all my dreams' - Stones to leave Man City
Περίληψη: England defender John Stones says he "lived all my dreams out" at Manchester City after confirming he will leave at the end of the season.
Link: https://www.bbc.com/sport/football/articles/clypwjeydnjo
--------------------------------------------------
THIS IS A STORY
Τίτλος: Sinner beats Norrie to equal historic winning run
Περίληψη: World number one Jannik Sinner's brilliant form continues as he reaches the quarter-finals of the Madrid Open with a straight-set win over Britain's Cameron Norrie.
Link: https://www.bbc.com/sport/tennis/articles/cd0p5vx1g34o
--------------------------------------------------
THIS IS A STORY
Τίτλος: Liked by Flintoff & different to Crawley - is Gay England's next opener?
Περίληψη: After his match-winning century for Durham, BBC Sport assesses whether Emilio Gay has the skills to be England's next Test opener.
Link: https://www.bbc.com/sport/cricket/articles/cy91937e94go
--------------------------------------------------

In [35]:
import pandas as pd

data = []

cards = doc.select(
    'div[data-testid="card-text-wrapper"], '
    'div[data-testid="chester-article"]'
)

for card in cards:
    title = card.select_one('h2[data-testid="card-headline"]')
    desc = card.select_one('p[data-testid="card-description"]')
    link = card.find_parent('a')

    if not title:
        continue

    title_text = title.get_text(strip=True)

    desc_text = desc.get_text(strip=True) if desc else "Δεν υπάρχει"

    if link and link.has_attr('href'):
        href = link['href']
        if href.startswith('/'):
            href = 'https://www.bbc.com' + href
    else:
        href = "Δεν βρέθηκε"

    # βάζουμε σε dict
    data.append({
        "Τίτλος": title_text,
        "Περίληψη": desc_text,
        "Link": href
    })

# δημιουργία dataframe
df = pd.DataFrame(data)
# save σε CSV
df.to_csv("bbc_news.csv", index=False, encoding="utf-8-sig")

In [40]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time

BASE_URL = "https://www.capital.gr"
URL = "https://www.capital.gr/eidiseis?page={}"

headers = {
    "User-Agent": "Mozilla/5.0"
}

data = []

for page in range(1, 10):
    print("Scraping page:", page)

    response = requests.get(URL.format(page), headers=headers, timeout=15)
    response.encoding = "utf-8"

    soup = BeautifulSoup(response.text, "html.parser")

    articles = soup.select("article, div[class*='article'], div[class*='news'], li")

    for article in articles:
        title_tag = article.find(["h2", "h3"])

        if not title_tag:
            continue

        title = title_tag.get_text(strip=True)

        if not title:
            continue

        a = title_tag.find_parent("a") or article.find("a")
        link = ""

        if a and a.has_attr("href"):
            link = urljoin(BASE_URL, a["href"])

        desc_tag = article.find("p")
        description = desc_tag.get_text(strip=True) if desc_tag else ""

        data.append({
            "page": page,
            "title": title,
            "description": description,
            "link": link
        })

    time.sleep(0.5)

df = pd.DataFrame(data)

df = df.drop_duplicates(subset=["title", "link"])

df.to_csv("capital_news_200_pages.csv", index=False, encoding="utf-8-sig")

print("Τέλος")
print("Σύνολο ειδήσεων:", len(df))
print(df.head())

Scraping page: 1
Scraping page: 2
Scraping page: 3
Scraping page: 4
Scraping page: 5
Scraping page: 6
Scraping page: 7
Scraping page: 8
Scraping page: 9
Τέλος
Σύνολο ειδήσεων: 162
   page                                              title  \
0     1  Συνάντηση Κ. Τασούλα με τον Κρις Ράιτ - "Η Ελλ...
2     1  Οι επενδύσεις διατηρούν τη δυναμική και μετά τ...
3     1  Συνάντηση Τραμπ με τον βασιλιά Κάρολο - "Οι ΗΠ...
4     1  Σ. Ζαχαράκη: Η Ελλάδα ενσωματώνει με ταχύτητα ...
5     1  ΗΠΑ: Οι θεωρίες συνωμοσίας που λένε ότι ο Τραμ...

                                         description  \
0  Πιο συγκεκριμένα, συζήτησαν για τη συνεργασία ...
2  Ομαλή μετάβαση από το ΤΑΑ στα νέα χρηματοδοτικ...
3   "Είναι ένα τεράστιο προνόμιο να σας καλωσορίζω".
4                      Επαφές στην Κωνσταντινούπολη.
5  Η τελευταία θεωρία λέει ότι ο Τραμπ είναι "μετ...

                                                link
0  https://www.capital.gr/politiki/3988249/sunant...
2  https://www.capital.gr/oikonomia/3988206/oi-ep...
3  https://www.capital.gr/diethni/3988247/sunanti...
4  https://www.capital.gr/politiki/3988244/s-zaxa...
5  https://www.capital.gr/diethni/3988242/ipa-oi-...

In [41]:
pd.DataFrame(data)

,page,title,description,link
0,1,"Συνάντηση Κ. Τασούλα με τον Κρις Ράιτ - ""Η Ελλ...","Πιο συγκεκριμένα, συζήτησαν για τη συνεργασία ...",https://www.capital.gr/politiki/3988249/sunant...
1,1,"Συνάντηση Κ. Τασούλα με τον Κρις Ράιτ - ""Η Ελλ...","Πιο συγκεκριμένα, συζήτησαν για τη συνεργασία ...",https://www.capital.gr/politiki/3988249/sunant...
2,1,Οι επενδύσεις διατηρούν τη δυναμική και μετά τ...,Ομαλή μετάβαση από το ΤΑΑ στα νέα χρηματοδοτικ...,https://www.capital.gr/oikonomia/3988206/oi-ep...
3,1,"Συνάντηση Τραμπ με τον βασιλιά Κάρολο - ""Οι ΗΠ...","""Είναι ένα τεράστιο προνόμιο να σας καλωσορίζω"".",https://www.capital.gr/diethni/3988247/sunanti...
4,1,Σ. Ζαχαράκη: Η Ελλάδα ενσωματώνει με ταχύτητα ...,Επαφές στην Κωνσταντινούπολη.,https://www.capital.gr/politiki/3988244/s-zaxa...
...,...,...,...,...
175,9,Unicef: Το Αφγανιστάν κινδυνεύει να χάσει ως κ...,Οι Ταλιμπάν έχουν περιορίσει σημαντικά τον αρι...,https://www.capital.gr/diethni/3988005/unicef-...
176,9,Επιχείρηση ανάταξης της κυβερνητικής φθοράς,"""Όχημα"" η οικονομία. Μηνύματα Μητσοτάκη σε αγο...",https://www.capital.gr/politiki/3988004/epixei...
177,9,Νέο άλμα για το πετρέλαιο καθώς οι αγορές περι...,Άλμα κοντά στο 3% σημειώνουν οι τιμές του αργο...,https://www.capital.gr/agores/3988003/neo-alma...
178,9,Ιαπωνία: Η κεντρική τράπεζα διατήρησε το βασικ...,Οι επιπτώσεις από την κρίση στη Μέση Ανατολή.,https://www.capital.gr/diethni/3988002/iaponia...
179,9,Εκδήλωση για τη σφαγή των Ναζί στο Δίστομο,Ιδιαίτερα φορτισμένη ήταν η ατμόσφαιρα κατά τη...,https://www.capital.gr/epikairotita/3988001/ek...

In [36]:
pd.DataFrame(data)

,Τίτλος,Περίληψη,Link
0,US political violence generates a familiar cyc...,"In modern America, it seems violence of this k...",https://www.bbc.com/news/articles/cje4eeyq27lo
1,United Arab Emirates to quit oil cartel Opec,"The UAE's decision, after nearly 60 years of m...",https://www.bbc.com/news/articles/cj4pxwlr52yo
2,Why Sam Altman and his former hero Elon Musk a...,The battle between the AI big hitters has larg...,https://www.bbc.com/news/articles/cn8dedv8w8xo
3,'It's bizarre': Californians grapple with reve...,People living near the man charged with the at...,https://www.bbc.com/news/articles/c392knk3w2jo
4,Watch: Jimmy Kimmel defends 'expectant widow' ...,First Lady Melania Trump described the joke as...,https://www.bbc.com/news/videos/c62d4n5rzr7o
5,Russian superyacht sails through Strait of Hor...,"The 141m-long vessel, linked to a close ally o...",https://www.bbc.com/news/articles/cm2pn8zdxdjo
6,The other life of US soldier accused of bettin...,The Army officer charged with using classified...,https://www.bbc.com/news/articles/clyxd5wrr0wo
7,Suspected gunman aged 89 held in Greece after ...,Δεν υπάρχει,https://www.bbc.com/news/articles/cyv2pmz2v86o
8,Canada's Carney launches a sovereign wealth fu...,Δεν υπάρχει,https://www.bbc.com/news/articles/c98m800r28qo
9,Ex-actor Nathan Chasing Horse jailed for at le...,Δεν υπάρχει,https://www.bbc.com/news/articles/cx218vkdvpgo
10,Man admits plotting attack on Taylor Swift con...,Δεν υπάρχει,https://www.bbc.com/news/articles/c05d5qgprjzo
11,Japan Airlines trials humanoid robots as groun...,Δεν υπάρχει,https://www.bbc.com/news/articles/cpwp87j1llvo
12,Watch as Sabastian Sawe's parents celebrate ma...,Emily and Simion Sawe share their pride at the...,https://www.bbc.com/news/videos/cn0pl57xlppo
13,Will Mexico City's airport be ready for the Wo...,The BBC takes a closer look at major renovatio...,https://www.bbc.com/news/videos/cz7231qx88qo
14,The man who exposed hundreds of British Museum...,Dr Ittai Gradel made global headlines after ex...,https://www.bbc.com/news/articles/c1mk2pr39k7o
15,Canada's Carney has enjoyed a long political h...,Global acclaim and domestic political gains ha...,https://www.bbc.com/news/articles/c70d249rd0go
16,Why Spotify has no button to filter out AI music,Music streamer Deezer allows users to filter o...,https://www.bbc.com/news/articles/cd7jpg4w181o
17,When Attenborough met the gorillas - the story...,Two new documentaries explore the the fascinat...,https://www.bbc.com/news/articles/ce9n794g42zo
18,France murder victim identified after 20 years...,Hakima Boukerouis is the fifth woman to be ide...,https://www.bbc.com/news/articles/ckg9g8pwggqo
19,Suspect charged with attempted assassination o...,Investigators say the 31-year-old California m...,https://www.bbc.com/news/articles/cew7wez72vxo
20,Third Ukrainian strike hits Russian oil refine...,Residents near a burning refinery in Tuapse ar...,https://www.bbc.com/news/articles/cvgzd4qk7qgo
21,NZ axes plan for WW2 sex slaves statue after J...,Tokyo had warned that installing the structure...,https://www.bbc.com/news/articles/c62r8g6m541o
22,Ghana's military hunts those behind convoy att...,Three civilians and seven gunmen were killed i...,https://www.bbc.com/news/articles/c172g50rz7jo
23,"Swarm of 10,000 bees settles on bike outside L...",The swarm gathers underneath the saddle of a b...,https://www.bbc.com/news/articles/c70vjx99w2vo
24,Ranking the players who could decide Champions...,Which players will prove key to their team’s c...,https://www.bbc.com/sport/football/articles/c5...
25,The tactical fluidity that makes PSG so impres...,Despite boasting squads that have included the...,https://www.bbc.com/sport/football/articles/cx...
26,World Championship quarter-finals - Higgins v ...,Watch live coverage and follow text updates of...,https://www.bbc.com/sport/snooker/live/cn0wk5w...
27,'I lived all my dreams' - Stones to leave Man ...,"England defender John Stones says he ""lived al...",https://www.bbc.com/sport/football/articles/cl...
28,Sinner beats Norrie to equal historic winning run,World number one Jannik Sinner's brilliant for...,https://www.bbc.com/sport/tennis/articles/cd0p...
29,Liked by Flintoff & different to Crawley - is ...,"After his match-winning century for Durham, BB...",https://www.bbc.com/sport/cricket/articles/cy9...

## ΒΗΜΑ ΤΕΣΣΕΡΑ: Χρησιμοποιούμε την είδηση για να πάρουμε την σύνοψη

Το ίδιο και πάλι! Αυτή τη φορά ψάχνουμε τις παραγράφους `p`.

In [ ]:
stories = doc.find_all('div', { 'class': 'gs-c-promo' })
for story in stories:
    print("THIS IS A STORY")
    headline = story.find('h3')
    print(headline.text)
    link = story.find('a')
    print(link['href'])
    summary = story.find('p')
    print(summary.text)

### Λείπουν elements

Αυτό μας έλειπε τώρα, ένα error! Συγκεκριμένα λέει ότι ...

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-20-e55795264040> in <module>()
          7     print(link['href'])
          8     summary = story.find('p')
    ----> 9     print(summary.text)

    AttributeError: 'NoneType' object has no attribute 'text'

Εφόσον το λάθος εμφανίστηκε από την στιγμή που βάλαμε το κομμάτι με το `summary` part, υποθέτουμε ότι το πρόβλημα είναι ότι δεν έχει κάθε μια **ιστορία από ένα summary**. Πώς θα το λύσουμε αυτό???!!!

Λοιπόν, μπορούμε να *ρωτάμε αν (if) η ιστορία έχει summary*. Αν έχει τότε μπορούμε να το χρησιμοποιήσουμε. Αν δεν έχει το αγνοούμε. **Είναι ένα απλό `if` statement**.

In [ ]:
stories = doc.find_all('div', { 'class': 'gs-c-promo' })
for story in stories:
    print("THIS IS A STORY")
    headline = story.find('h3')
    print(headline.text)
    link = story.find('a')
    print(link['href'])
    summary = story.find('p')
    if summary:
        print(summary.text)

## Ας το σώσουμε ως CSV

Τώρα που έχουμε όλα τα στοιχεία που θέλαμε μπορούμε να τα μετατρέψουμε σε ένα CSV. Υπάρχουν 3 βήματα για τη μετατροπή σε CSV:
    
1. **Ξεκινάμε με μια άδεια λίστα:** Κάθε ιστορία που βρίσκουμε, την προσθέτουμε στη λίστα
2. **Φτιάχνουμε ένα λεξικό** για κάθε μια ιστορία
3. **Μετατρέπουμε τη λίστα σε ένα DataFrame**, μετά
4. **Εξάγουμε το DataFrame σε ένα CSV**

Η δημιουργία του λεξικού μπορεί να είναι λίγο περίπλοκη, οπότε ας δούμε **2 διαφορετικούς τρόπους να το κάνουμε**.

### Μέθοδος 1η: Όλα μαζί

Θα φτιάξουμε το λεξικό `story_dict` απευθείας και μετά θα το προσθέσουμε στη λίστα `stories_list`.

In [ ]:
# Ξεκινάμε με μια άδεια λίστα
stories_list = []
stories = doc.find_all('div', { 'class': 'gs-c-promo' })
for story in stories:
    headline = story.find('h3')
    link = story.find('a')
    summary = story.find('p')
    # Έχει η ιστορία summary?
    if summary:
        summary_text = summary.text
    else:
        summary_text = ''

        # Φτιάξε ένα λεξικό αν ΕΧΕΙ summary
    story_dict = {
            'headline': headline.text,
            'url': link['href'],
            'summary': summary_text
        }

    # Πρόσθεσε το λέξικο στη λίστα
    stories_list.append(story_dict)

print(stories_list)

# Τώρα που τελειώσαμε μετέτρεψε το σε CSV και αποθήκευσε το.
# Αν δεν χρησιμοποιήσετε το index=False, θα έχετε ένα άσχημο dataframe!
import pandas as pd
df = pd.DataFrame(stories_list)
df.to_csv("bbc.csv", index=False)

### Μέθοδος 2η: Γεμίζοντας τα κενά

Για αυτή τη μέθοδο θα φτιάξουμε πρώτα το λεξικό μας `story_dict` και μετά θα το γεμίζουμε με τα στοιχεία που υπάρχουν.

In [ ]:
# Ξεκινάμε με μια άδεια λίστα
stories_list = []
stories = doc.find_all('div', { 'class': 'gs-c-promo' })
for story in stories:
    # Φτιάχνουμε ένα λεξικό χωρίς τίποτα
    story_dict = {}
    headline = story.find('h3')
    if headline:
        story_dict['headline'] = headline.text
    link = story.find('a')
    if link:
        story_dict['url'] = link['href']
    summary = story.find('p')
    if summary:
        story_dict['summary'] = summary.text
    # Προσθέτουμε το λεξικό στη λίστα
    stories_list.append(story_dict)

# Τώρα που τελειώσαμε μετέτρεψε το σε CSV και αποθήκευσε το.
# Αν δεν χρησιμοποιήσετε το index=False, θα έχετε ένα άσχημο dataframe!
import pandas as pd
df = pd.DataFrame(stories_list)
df.to_csv("bbc.csv", index=False)